---
- name: Check for supported operating system on target
  fail:
    msg: "The operating system of the target machine ({{ inventory_hostname }}) is not currently supported or tested."
  when: ansible_distribution != 'Ubuntu' or ansible_distribution_release not in ['precise', 'trusty']

- name: Include Debian specific tasks
  include: Debian.yml
  when: ansible_os_family == 'Debian' and sudoers_cfg is defined

# ToDo:
#
#- name: Include RedHat specific tasks
#  include: RedHat.yml
#  when: ansible_os_family == 'RedHat'
#
#- name: Include Suse specific tasks
#  include: Suse.yml
#  when: ansible_os_family == 'Suse'
